version: '2'

services:
  db:
    image: mariadb:10
    environment:
      - "MYSQL_DATABASE=data"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=app"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"

  php:
    image: imarcagency/php-apache:latest
    environment:
      - "APACHE_ROOT=/var/www/web"
    ports:
      - "80:80"
    links:
      - db
    depends_on:
      - db
    volumes:
      - "./:/var/www"
