version: '2'

services:
  php:
    image: imarcagency/php-apache:latest
    environment:
      - "APACHE_ROOT=/var/www/web"
    volumes:
      - "./:/var/www"
      - "uploads:/var/www/web/wp-content/uploads"

volumes:
  uploads:

