version: '2'

services:
  db:
    image: mariadb:10
    environment:
      - "MYSQL_DATABASE=wordpress"
      - "MYSQL_USER=wordpress"
      - "MYSQL_PASSWORD=wordpress"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"

  php:
    image: jeffturcotte/php:latest
    links:
      - db
    depends_on:
      - db
    volumes:
      - "./:/var/www/"

  nginx:
    image: jeffturcotte/nginx-fastcgi:latest
    ports:
      - "80:80"
    environment:
      - "NGINX_ROOT=/var/www/public"
    links:
      - php
    volumes:
      - "./:/var/www"
